# first time after startup also run this:
library(languageR)
library(plyr)
library(dplyr)
library(knitr)
library(fitdistrplus)
library(MESS)
library(gridExtra)
library(data.table)
library(magrittr)

# Clean workspace, uncomment to use
#rm(list=ls())

# script body --------------------------------------------------------------

# File list and initialization of data set --------------------------------

# To ensure comparability with previous studies using amperometry with glutamate-coated multi-electrode-arrays, several key parameters
# such as amplitude and baselien were calculated using the Fast analysis program version 6.1 (https://fastanalysis.wordpress.com/fast-analysis/)
# by Jason Burmeister. These are saved in the stimulation files, which are loaded in this step.

s983 <- fread("983_stimulations.txt",header=TRUE,sep="\t") # AAV-DJ Pitx2-Cre new Arduino, Injection by Thomas
s984 <- fread("984_stimulations.txt",header=TRUE,sep="\t") # AAV-DJ Pitx2-Cre new Arduino, Injection by Thomas
s986 <- fread("986_stimulations.txt",header=TRUE,sep="\t") # AAV-DJ Pitx2-Cre new Arduino, Injection by Thomas
s993 <- fread("993_stimulations.txt",header=TRUE,sep="\t") # AAV-DJ Pitx2-Cre new Arduino, Injection by Thomas
s974 <- fread("974_stimulations.txt",header=TRUE,sep="\t") # AAV-DJ Pitx2-Cre new Arduino, Injection by Thomas
s972 <- fread("972_stimulations.txt",header=TRUE,sep="\t") # AAV-DJ Pitx2-Cre new Arduino, Injection by Thomas
s981 <- fread("981_stimulations.txt",header=TRUE,sep="\t") # AAV-DJ Pitx2-Cre new Arduino, Injection by Thomas

s1437 <- fread("1437_stimulations.txt",header=TRUE,sep="\t") # AAV-DJ No CHR2 ! Pitx2-Cre new Arduino, Injection by Thomas
s1971 <- fread("1971_stimulations.txt",header=TRUE,sep="\t") # AAV5 No CHR2 ! Pitx2-Cre new Arduino, Injection by Thomas
s2086 <- fread("2086_stimulations.txt",header=TRUE,sep="\t") # AAV-DJ No CHR2 ! Pitx2-Cre new Arduino, Injection by Thomas
s2087 <- fread("2087_stimulations.txt",header=TRUE,sep="\t") # AAV5 No CHR2 ! Pitx2-Cre new Arduino, Injection by Thomas
s6323 <- fread("6323_stimulations.txt",header=TRUE,sep="\t") # AAV-DJ No CHR2 ! Pitx2-Cre new Arduino, Injection by Thomas
s6231 <- fread("6231_stimulations.txt",header=TRUE,sep="\t") # AAV-DJ No CHR2 ! Pitx2-Cre new Arduino, Injection by Thomas

stimulation_list <- list(s983,s984,s986,s993,s974,s972,s981,s1437,s2086,s1971,s2087,s6231,s6323)

# The rawdata files are CSV exports of the timeseries recorded in the FASTRecording program. These files are generated by using the export
# function of ther FAST analysis program 6.1. The first column (V1) contains the TTL informatiojn sent by the amplifier, V2-V5 correspond to
# electrode channels 1,2,3,4. V6-V9 correspond to the channel pairs generated by self-referencing of the electrode array (glutamate-sensitive - sentinel channel).
# V6 = 1-3
# V7 = 2-4 or 2-3 --> based on the calculation in the FAST analysis program, both of these combinations will be exported to V6, in the following
# the file is annotated with which channel pair was used during export.

# V8-V9 are exported as (sentinal - glutamate-sensitive channel)
# V8 = 3-2
# V9 = 4-1

# One channel pair was used for analysis. This was based on the in vitro calibration results. If a channel was damaged during implantation,
# the best remaining pair was used instead. For the results of the in vitro calibration see the file: supplementarytable1.pdf

# The chosen channel pair is copied into the "used" column, the remaining columns are later dropped

raw983 <- fread("rawdata983.csv",header=FALSE,sep=",") # AAV-DJ Pitx2-Cre new Arduino, Injection by Thomas
raw983$used <- raw983$V7 #copy signal from 2-4 channel pair

raw984 <- fread("rawdata984.csv",header=FALSE,sep=",") # AAV-DJ Pitx2-Cre new Arduino, Injection by Thomas
raw984$used <- raw984$V7 #copy signal from 2-4 channel pair

raw986 <- fread("rawdata986.csv",header=FALSE,sep=",") # AAV-DJ Pitx2-Cre new Arduino, Injection by Thomas
raw986$used <- raw986$V7 #copy signal from 2-4 channel pair

raw993 <- fread("rawdata993.csv",header=FALSE,sep=",") # AAV-DJ Pitx2-Cre new Arduino, Injection by Thomas
raw993$used <- raw993$V7 #copy signal from 2-4 channel pair

raw974 <- fread("rawdata974.csv",header=FALSE,sep=",") # AAV-DJ Pitx2-Cre new Arduino, Injection by Thomas
raw974$used <- raw974$V7 #copy signal from 2-3 channel pair

raw972 <- fread("rawdata972.csv",header=FALSE,sep=",") # AAV-DJ Pitx2-Cre new Arduino, Injection by Thomas
raw972$used <- raw972$V7 #copy signal from 2-3 channel pair

raw981 <- fread("rawdata981.csv",header=FALSE,sep=",") # AAV-DJ Pitx2-Cre new Arduino, Injection by Thomas
raw981$used <- raw981$V7 #copy signal from 2-4 channel pair

# EYFP control
raw1437 <- fread("rawdata1437.csv",header=FALSE,sep=",") # AAV-DJ EYFP only Pitx2-Cre new Arduino, Injection by Thomas
raw1437$used <- raw1437$V7 #copy signal from 2-4 channel pair

raw2086 <- fread("rawdata2086.csv",header=FALSE,sep=",") # AAV-DJ EYFP only Pitx2-Cre new Arduino, Injection by Thomas
raw2086$used <- raw2086$V6 #copy signal from 1-3 channel pair

raw1971 <- fread("rawdata1971.csv",header=FALSE,sep=",") # AAV5 EYFP only Pitx2-Cre new Arduino, Injection by Thomas
raw1971$used <- raw1971$V6 #copy signal from 1-3 channel pair

raw2087 <- fread("rawdata2087.csv",header=FALSE,sep=",") # AAV5 EYFP only Pitx2-Cre new Arduino, Injection by Thomas
raw2087$used <- raw2087$V7 #copy signal from 2-4 channel pair

raw6231 <- fread("rawdata6231.csv",header=FALSE,sep=",") # AAV-DJ EYFP only Pitx2-Cre new Arduino, Injection by Thomas
raw6231$used <- raw6231$V7 #copy signal from 2-4 channel pair

raw6323 <- fread("rawdata6323.csv",header=FALSE,sep=",") # AAV-DJ EYFP only Pitx2-Cre new Arduino, Injection by Thomas
raw6323$used <- raw6323$V6 #copy signal from 1-3 channel pair


# By default, the raw data files obtained from the FastRecording program will contain the marker number for each event 
# in the first column, however, only when the TTL was send from the amplifier. Otherwise, the marker is set to "0". The
# function getEventAndReltime will set the marker to the current event number for a time span of 10 seconds before and 20 seconds after
# the TTL was sent and calculates a new time variable reltime which is dependent on the position of the TTL. This allows for
# time-matching of the individual events. The first event (1) is the start marker, while the last events in the list are 
# generated upon completion of the recording. All of these should be omitted.

getEventAndReltime <- function(x) {
  iter <- head(x[V1>1,V1],-3) #omit last events and start event
  for (i in iter) {
    x <- x[(x[V1==i,time]-100):(x[V1==i,time]+200),event := i] # Set event number
    x <- x[(x[V1==i,time]-100):(x[V1==i,time]+200),reltime := -100:200] # Generate relative time in relation to the event
  }
  return (x)
}

#create list of data.tables for all experiments
rawdata_list <- list(raw983,raw984,raw986,raw993,raw974,raw972,raw981,raw1437,raw2086,raw1971,raw2087,raw6231,raw6323)
#drop unneeded columns, keep only TTL register (v1) and used electrode channel (used)
rawdata_list <- rawdata_list %>% lapply(function(x) x[,c(1,10)]) 
#add columns for time and placeholder columns for event and relative time (reltime)
rawdata_list <- rawdata_list %>% lapply(function(x) cbind(x, "time"=1:nrow(x))) 
rawdata_list <- rawdata_list %>% lapply(function(x) cbind(x, "event"=rep(0,nrow(x)))) 
rawdata_list <- rawdata_list %>% lapply(function(x) cbind(x, "reltime"=rep(0,nrow(x))))
#add event based on TTL signal in the surrounding
rawdata_list <- rawdata_list %>% lapply(function(x) getEventAndReltime(x)) 

# Here, events not corresponding to optogenetic stimulation 
# (intermediate markers for switch of holding potential and the like are removed). In the following, the events in the rawdata file are joined
# with the events in the stimulation files

#join rawdata list with stimulation results
joined_list <- list()
for (i in 1:length(rawdata_list)){
  joined_list[[i]] <- inner_join(rawdata_list[[i]],stimulation_list[[i]],by="event")
}
joined_list <- joined_list %>% lapply(function(x) mutate(x,normalizedAmp=used-Baseline)) 
joined_list <- joined_list %>% lapply(function(x) mutate(x,reltimeSec=reltime/10)) 

# Convert the list of data frames to a single data frame containing all data

rawfiles <- rbind(joined_list[[1]],joined_list[[2]],joined_list[[3]],joined_list[[4]],joined_list[[5]],joined_list[[6]],joined_list[[7]],joined_list[[8]],joined_list[[9]],joined_list[[10]],joined_list[[11]],joined_list[[12]],joined_list[[13]])
rawfiles$genotype <- as.factor(rawfiles$genotype)
rawfiles$construct <- as.factor(rawfiles$construct)
rawfiles$reltimeSec <- rawfiles$reltime/10 # Recordings were obtained at 10Hz recording frequency. This step converts the time to seconds


### averaging signal
SSumAv_Event <- ddply(rawfiles, c("genotype","reltime","protocol","pulse","frequency","voltage","ID","construct"), summarise,
                      normAmp = mean(normalizedAmp),       
                      mean = mean(used)
)

SSumAv_Event025 <- subset(SSumAv_Event,voltage==0.25)
SSumAv_Event07 <- subset(SSumAv_Event,voltage==0.7)
SSumAv_Event07$corrSignal <- SSumAv_Event07$normAmp - SSumAv_Event025$normAmp

SSumAv_EventID <- ddply(rawfiles, c("genotype","reltime","protocol","pulse","frequency","voltage","construct"), summarise,
                        normAmp = mean(normalizedAmp),
                        mean = mean(used)
)
SSumAv_EventID$reltimeSec <- SSumAv_EventID$reltime / 10

SSumAv_EventID_1 <- subset(SSumAv_EventID,protocol==1)
SSumAv_EventID_2 <- subset(SSumAv_EventID,protocol==2)

SSumAv_EventID025 <- subset(SSumAv_EventID,voltage==0.25)
SSumAv_EventID07 <- subset(SSumAv_EventID,voltage==0.7)
SSumAv_EventID07$corrSignal <- SSumAv_EventID07$normAmp - SSumAv_EventID025$normAmp

group.colorsConstruct <- c("EYFP" = "#999999", "ChR2-EYFP" = "#39A848")
group.colorsVoltage<- c("0.7" = "#2A4C99", "0.25" = "#555555")

#### Decay functions ---------

# The following will model the events of all stimulation as linear decay for the initial phase and exponential decay in the late phase and 
# combine the results according to protocol, frequency and genotype.
# THe function generating the exponential decay will generate a warning message, which has no effect on the results.

Decay_constants_Sum_exp <- ddply(SSumAv_EventID07[(SSumAv_EventID07$reltimeSec >= 0) & (SSumAv_EventID07$reltimeSec <= 2),], c("genotype","construct","protocol","pulse","frequency"), summarise,
                                 T1 = 1,
                                 T2 = 1.5,
                                 a1 = summary(lm(corrSignal[(reltimeSec >= T1) & (reltimeSec <= T2)] ~ (reltimeSec[(reltimeSec >= T1) & (reltimeSec <= T2)])))$coefficients[2],
                                 a0 = summary(lm(corrSignal[(reltimeSec >= T1) & (reltimeSec <= T2)] ~ (reltimeSec[(reltimeSec >= T1) & (reltimeSec <= T2)])))$coefficients[1],
                                 r2_linear = summary(lm(corrSignal[(reltimeSec >= T1) & (reltimeSec <= T2)] ~ (reltimeSec[(reltimeSec >= T1) & (reltimeSec <= T2)])))$adj.r.squared,
                                 lambda = summary(lm(log(corrSignal[(reltimeSec >= T2)]) ~ (reltimeSec[(reltimeSec >= T2)])))$coefficients[2],
                                 tau = -1/lambda,
                                 b = summary(lm(log(corrSignal[(reltimeSec >= T2)]) ~ (reltimeSec[(reltimeSec >= T2)])))$coefficients[1],
                                 r2 = summary(lm(log(corrSignal[(reltimeSec >= T2)]) ~ (reltimeSec[(reltimeSec >= T2)])))$adj.r.squared
)

Decay_constants_Sum_exp <- ddply(SSumAv_EventID07[(SSumAv_EventID07$reltimeSec >= 0) & (SSumAv_EventID07$reltimeSec <= 2),], c("genotype","construct","protocol","pulse","frequency"), summarise,
                   correction = 0,
                   Trise = 1,
                   Tstart = 1.5,
                   a1 = summary(lm(corrSignal[(reltimeSec >= Trise) & (reltimeSec <= Tstart)] ~ (reltimeSec[(reltimeSec >= Trise) & (reltimeSec <= Tstart)])))$coefficients[2],
                   a0 = summary(lm(corrSignal[(reltimeSec >= Trise) & (reltimeSec <= Tstart)] ~ (reltimeSec[(reltimeSec >= Trise) & (reltimeSec <= Tstart)])))$coefficients[1],
                   r2_linear = summary(lm(corrSignal[(reltimeSec >= Trise) & (reltimeSec <= Tstart)] ~ (reltimeSec[(reltimeSec >= Trise) & (reltimeSec <= Tstart)])))$adj.r.squared,
                   lambda = summary(lm(log(corrSignal[(reltimeSec >= Tstart)] + correction) ~ (reltimeSec[(reltimeSec >= Tstart)])))$coefficients[2],
                   tau = -1/lambda,
                   b = summary(lm(log(corrSignal[(reltimeSec >= Tstart)] + correction) ~ (reltimeSec[(reltimeSec >= Tstart)])))$coefficients[1],
                   r2 = summary(lm(log(corrSignal[(reltimeSec >= Tstart)] + correction) ~ (reltimeSec[(reltimeSec >= Tstart)])))$adj.r.squared
                   )

save.image(file = "output_signalprocessing.RData", safe = TRUE)

